language: python
sudo: false

before_install:
  - pip install behave
  - rvm install 2.5
  - rvm use 2.5
  - gem install nokogiri -v 1.10.10
  - gem install hiptest-publisher
  - "hiptest-publisher -c behave.conf --only=features,step_definitions --test-run-id=536761"

script:
 - behave --format json -o results/results.json

after_script:
 - hiptest-publisher -c behave.conf --push=results/results.json --test-run-id=536761
